services:
  - type: web
    name: examination-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
