services:
  - type: web
    name: examination-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    healthCheckPath: /health
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: "1"
